/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatWorldcupRouteImport } from './routes/_chat.worldcup'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatAutomationsRouteImport } from './routes/_chat.automations'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatWorkspaceIndexRouteImport } from './routes/_chat.workspace.index'
import { Route as ChatStudioIndexRouteImport } from './routes/_chat.studio.index'
import { Route as ChatPullRequestsIndexRouteImport } from './routes/_chat.pull-requests.index'
import { Route as ChatKanbanIndexRouteImport } from './routes/_chat.kanban.index'
import { Route as ChatAutomationsIndexRouteImport } from './routes/_chat.automations.index'
import { Route as ChatWorkspaceWorkspaceIdRouteImport } from './routes/_chat.workspace.$workspaceId'
import { Route as ChatKanbanProjectIdRouteImport } from './routes/_chat.kanban.$projectId'
import { Route as ChatAutomationsAutomationIdRouteImport } from './routes/_chat.automations.$automationId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorldcupRoute = ChatWorldcupRouteImport.update({
  id: '/worldcup',
  path: '/worldcup',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsRoute = ChatAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceIndexRoute = ChatWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatStudioIndexRoute = ChatStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsIndexRoute = ChatPullRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPullRequestsRoute,
} as any)
const ChatKanbanIndexRoute = ChatKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsIndexRoute = ChatAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAutomationsRoute,
} as any)
const ChatWorkspaceWorkspaceIdRoute =
  ChatWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatKanbanProjectIdRoute = ChatKanbanProjectIdRouteImport.update({
  id: '/kanban/$projectId',
  path: '/kanban/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsAutomationIdRoute =
  ChatAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ChatAutomationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/automations': typeof ChatAutomationsRouteWithChildren
  '/plugins': typeof ChatPluginsRoute
  '/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/worldcup': typeof ChatWorldcupRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/automations/': typeof ChatAutomationsIndexRoute
  '/kanban/': typeof ChatKanbanIndexRoute
  '/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/studio/': typeof ChatStudioIndexRoute
  '/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/worldcup': typeof ChatWorldcupRoute
  '/': typeof ChatIndexRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/automations': typeof ChatAutomationsIndexRoute
  '/kanban': typeof ChatKanbanIndexRoute
  '/pull-requests': typeof ChatPullRequestsIndexRoute
  '/studio': typeof ChatStudioIndexRoute
  '/workspace': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/automations': typeof ChatAutomationsRouteWithChildren
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/worldcup': typeof ChatWorldcupRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/_chat/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/_chat/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/_chat/automations/': typeof ChatAutomationsIndexRoute
  '/_chat/kanban/': typeof ChatKanbanIndexRoute
  '/_chat/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/_chat/studio/': typeof ChatStudioIndexRoute
  '/_chat/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/automations'
    | '/plugins'
    | '/pull-requests'
    | '/settings'
    | '/worldcup'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/workspace/$workspaceId'
    | '/automations/'
    | '/kanban/'
    | '/pull-requests/'
    | '/studio/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/worldcup'
    | '/'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/workspace/$workspaceId'
    | '/automations'
    | '/kanban'
    | '/pull-requests'
    | '/studio'
    | '/workspace'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/automations'
    | '/_chat/plugins'
    | '/_chat/pull-requests'
    | '/_chat/settings'
    | '/_chat/worldcup'
    | '/_chat/'
    | '/_chat/automations/$automationId'
    | '/_chat/kanban/$projectId'
    | '/_chat/workspace/$workspaceId'
    | '/_chat/automations/'
    | '/_chat/kanban/'
    | '/_chat/pull-requests/'
    | '/_chat/studio/'
    | '/_chat/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/worldcup': {
      id: '/_chat/worldcup'
      path: '/worldcup'
      fullPath: '/worldcup'
      preLoaderRoute: typeof ChatWorldcupRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations': {
      id: '/_chat/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ChatAutomationsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace/': {
      id: '/_chat/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof ChatWorkspaceIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/studio/': {
      id: '/_chat/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof ChatStudioIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests/': {
      id: '/_chat/pull-requests/'
      path: '/'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof ChatPullRequestsIndexRouteImport
      parentRoute: typeof ChatPullRequestsRoute
    }
    '/_chat/kanban/': {
      id: '/_chat/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof ChatKanbanIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/': {
      id: '/_chat/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof ChatAutomationsIndexRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/workspace/$workspaceId': {
      id: '/_chat/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof ChatWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/kanban/$projectId': {
      id: '/_chat/kanban/$projectId'
      path: '/kanban/$projectId'
      fullPath: '/kanban/$projectId'
      preLoaderRoute: typeof ChatKanbanProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/$automationId': {
      id: '/_chat/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof ChatAutomationsAutomationIdRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
  }
}

interface ChatAutomationsRouteChildren {
  ChatAutomationsAutomationIdRoute: typeof ChatAutomationsAutomationIdRoute
  ChatAutomationsIndexRoute: typeof ChatAutomationsIndexRoute
}

const ChatAutomationsRouteChildren: ChatAutomationsRouteChildren = {
  ChatAutomationsAutomationIdRoute: ChatAutomationsAutomationIdRoute,
  ChatAutomationsIndexRoute: ChatAutomationsIndexRoute,
}

const ChatAutomationsRouteWithChildren = ChatAutomationsRoute._addFileChildren(
  ChatAutomationsRouteChildren,
)

interface ChatPullRequestsRouteChildren {
  ChatPullRequestsIndexRoute: typeof ChatPullRequestsIndexRoute
}

const ChatPullRequestsRouteChildren: ChatPullRequestsRouteChildren = {
  ChatPullRequestsIndexRoute: ChatPullRequestsIndexRoute,
}

const ChatPullRequestsRouteWithChildren =
  ChatPullRequestsRoute._addFileChildren(ChatPullRequestsRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatAutomationsRoute: typeof ChatAutomationsRouteWithChildren
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatWorldcupRoute: typeof ChatWorldcupRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatKanbanProjectIdRoute: typeof ChatKanbanProjectIdRoute
  ChatWorkspaceWorkspaceIdRoute: typeof ChatWorkspaceWorkspaceIdRoute
  ChatKanbanIndexRoute: typeof ChatKanbanIndexRoute
  ChatStudioIndexRoute: typeof ChatStudioIndexRoute
  ChatWorkspaceIndexRoute: typeof ChatWorkspaceIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatAutomationsRoute: ChatAutomationsRouteWithChildren,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatPullRequestsRoute: ChatPullRequestsRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatWorldcupRoute: ChatWorldcupRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatKanbanProjectIdRoute: ChatKanbanProjectIdRoute,
  ChatWorkspaceWorkspaceIdRoute: ChatWorkspaceWorkspaceIdRoute,
  ChatKanbanIndexRoute: ChatKanbanIndexRoute,
  ChatStudioIndexRoute: ChatStudioIndexRoute,
  ChatWorkspaceIndexRoute: ChatWorkspaceIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
