/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatWorkspaceIndexRouteImport } from './routes/_chat.workspace.index'
import { Route as ChatKanbanIndexRouteImport } from './routes/_chat.kanban.index'
import { Route as ChatWorkspaceWorkspaceIdRouteImport } from './routes/_chat.workspace.$workspaceId'
import { Route as ChatKanbanProjectIdRouteImport } from './routes/_chat.kanban.$projectId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceIndexRoute = ChatWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatKanbanIndexRoute = ChatKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceWorkspaceIdRoute =
  ChatWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatKanbanProjectIdRoute = ChatKanbanProjectIdRouteImport.update({
  id: '/kanban/$projectId',
  path: '/kanban/$projectId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/kanban/': typeof ChatKanbanIndexRoute
  '/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/kanban': typeof ChatKanbanIndexRoute
  '/workspace': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/_chat/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/_chat/kanban/': typeof ChatKanbanIndexRoute
  '/_chat/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/kanban/$projectId'
    | '/workspace/$workspaceId'
    | '/kanban/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/'
    | '/kanban/$projectId'
    | '/workspace/$workspaceId'
    | '/kanban'
    | '/workspace'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/plugins'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/kanban/$projectId'
    | '/_chat/workspace/$workspaceId'
    | '/_chat/kanban/'
    | '/_chat/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace/': {
      id: '/_chat/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof ChatWorkspaceIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/kanban/': {
      id: '/_chat/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof ChatKanbanIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace/$workspaceId': {
      id: '/_chat/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof ChatWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/kanban/$projectId': {
      id: '/_chat/kanban/$projectId'
      path: '/kanban/$projectId'
      fullPath: '/kanban/$projectId'
      preLoaderRoute: typeof ChatKanbanProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatKanbanProjectIdRoute: typeof ChatKanbanProjectIdRoute
  ChatWorkspaceWorkspaceIdRoute: typeof ChatWorkspaceWorkspaceIdRoute
  ChatKanbanIndexRoute: typeof ChatKanbanIndexRoute
  ChatWorkspaceIndexRoute: typeof ChatWorkspaceIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatKanbanProjectIdRoute: ChatKanbanProjectIdRoute,
  ChatWorkspaceWorkspaceIdRoute: ChatWorkspaceWorkspaceIdRoute,
  ChatKanbanIndexRoute: ChatKanbanIndexRoute,
  ChatWorkspaceIndexRoute: ChatWorkspaceIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
